<?php

namespace Database\Seeders;

use App\Models\Especie;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EspeciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Definir los nombres de los departamentos
        $especies = [
            ['departamento_id'	=>	1	,'detalle' => '	ADQUISICIÓN MATERIALES DE OFICINA	'],
            ['departamento_id'	=>	1	,'detalle' => '	ADQUISICIÓN UTILES DE ASEO	'],
            ['departamento_id'	=>	1	,'detalle' => '	INSUMOS, REP Y AC COMPUTACIONALES	'],
            ['departamento_id'	=>	1	,'detalle' => '	ADQUISICIÓN DE MATERIALES DE CONSTRUCCIÓN	'],
            ['departamento_id'	=>	1	,'detalle' => '	ADQUISICIÓN DE PLACAS IDENTIFICACION CUARTELES	'],
            ['departamento_id'	=>	1	,'detalle' => '	MANTENCIÓN SALA DE CALDERA	'],
            ['departamento_id'	=>	1	,'detalle' => '	MANTENCIÓN EQUIPOS AIRE ACONDICIONADO	'],
            ['departamento_id'	=>	1	,'detalle' => '	SERVICIO DE ASEO DIGCAR	'],
            ['departamento_id'	=>	1	,'detalle' => '	MANTENCIÓN SALA DE BOMBAS	'],
            ['departamento_id'	=>	2	,'detalle' => '	BANDERA INSTITUCIONAL ESTAMPADA POR SUBLIMACIÓN 	'],
            ['departamento_id'	=>	2	,'detalle' => '	BANDERA NACIONAL PARA CARABINEROS DE CHILE 	'],
            ['departamento_id'	=>	2	,'detalle' => '	BOTÍN DE SEGURIDAD	'],
            ['departamento_id'	=>	2	,'detalle' => '	BLUSA CREMA (ACIPOL)	'],
            ['departamento_id'	=>	2	,'detalle' => '	CALCETIN BAMBOO  	'],
            ['departamento_id'	=>	2	,'detalle' => '	CALCETIN PARA BOTA COMANDO 	'],
            ['departamento_id'	=>	2	,'detalle' => '	CAMISA UNIFORME MANGA CORTA FEMENINA SIN VELCRO 	'],
            ['departamento_id'	=>	2	,'detalle' => '	CAMISA BLANCA MANGA CORTA	'],
            ['departamento_id'	=>	2	,'detalle' => '	CASCO CICLISTA 	'],
            ['departamento_id'	=>	2	,'detalle' => '	CINTURÓN TEJIDO   	'],
            ['departamento_id'	=>	2	,'detalle' => '	CINTURON OPERATIVO (NUEVO VESTUARIO)	'],
            ['departamento_id'	=>	2	,'detalle' => '	CORTAVIENTO UNIDAD ESPECIALIZADA Y SIP	'],
            ['departamento_id'	=>	2	,'detalle' => '	CONJUNTO INTERIOR TÉRMICO UNISEX   	'],
            ['departamento_id'	=>	2	,'detalle' => '	CORBATA DE UNIFORME FEMENINA  	'],
            ['departamento_id'	=>	2	,'detalle' => '	CORBATA DE UNIFORME MASCULINA  	'],
            ['departamento_id'	=>	2	,'detalle' => '	GORRA DE SERVICIO OFICIAL SUBALTERNO FEMENINO  	'],
            ['departamento_id'	=>	2	,'detalle' => '	GORRA DE SERVICIO OFICIAL SUBALTERNO MASC  	'],
            ['departamento_id'	=>	2	,'detalle' => '	GORRA DE SERVICIO PNI FEMENINO  	'],
            ['departamento_id'	=>	2	,'detalle' => '	GORRAS OFICIALES SUPERIORES MASCULINO 	'],
            ['departamento_id'	=>	2	,'detalle' => '	GORRAS OFICIALES SUPERIORES FEMENINO 	'],
            ['departamento_id'	=>	2	,'detalle' => '	GORRO TIPO CHAPKA  	'],
            ['departamento_id'	=>	2	,'detalle' => '	GUANTES DE MOTORISTA COLOR BLANCO 	'],
            ['departamento_id'	=>	2	,'detalle' => '	LOGO CORPORATIVO UNIDAD	'],
            ['departamento_id'	=>	2	,'detalle' => '	POLERA CICLISTA 	'],
            ['departamento_id'	=>	2	,'detalle' => '	POLERA PIQUE VERDE UNISEX  	'],
            ['departamento_id'	=>	2	,'detalle' => '	PANTALÓN CICLISTA PIERNA DESMONTABLE   	'],
            ['departamento_id'	=>	2	,'detalle' => '	POLAR INTRACUARTEL NEGRO	'],
            ['departamento_id'	=>	2	,'detalle' => '	PALAS CAMISA CABO 2DO A SOM	'],
            ['departamento_id'	=>	2	,'detalle' => '	PALAS CAMISA SUBTTE A CORONEL	'],
            ['departamento_id'	=>	2	,'detalle' => '	PANTALON UNIDAD ESPECIALIZADA Y SIP	'],
            ['departamento_id'	=>	2	,'detalle' => '	TENIDA MATERNAL	'],
            ['departamento_id'	=>	2	,'detalle' => '	VESTUARIO OFICIALES GENERALES   	'],
            ['departamento_id'	=>	2	,'detalle' => '	ZAPATILLA CICLISTA	'],
            ['departamento_id'	=>	2	,'detalle' => '	ZAPATO OPERATIVO C/CORDON FEMENINO 	'],
            ['departamento_id'	=>	2	,'detalle' => '	ZAPATO SALIDA FEMENINO 	'],
            ['departamento_id'	=>	2	,'detalle' => '	BEATLE OPERATIVO UNISEX (NUEVO MODELO) 	'],
            ['departamento_id'	=>	2	,'detalle' => '	BOTÍN OPERATIVO MODELO FEMENINO  	'],
            ['departamento_id'	=>	2	,'detalle' => '	BOTA CUERO CAFÉ FEMENINA	'],
            ['departamento_id'	=>	2	,'detalle' => '	BOTA TACTICA ESTANDAR   	'],
            ['departamento_id'	=>	2	,'detalle' => '	CAMISA UNIFORME MANGA CORTA FEMENINA  	'],
            ['departamento_id'	=>	2	,'detalle' => '	CAMISA UNIFORME MANGA CORTA MASCULINA  	'],
            ['departamento_id'	=>	2	,'detalle' => '	CAMISA UNIFORME MANGA CORTA MASCULINA SIN VELCRO 	'],
            ['departamento_id'	=>	2	,'detalle' => '	CAMISA UNIFORME MANGA LARGA FEMENINA  	'],
            ['departamento_id'	=>	2	,'detalle' => '	CASACA OPERATIVA UNISEX  	'],
            ['departamento_id'	=>	2	,'detalle' => '	GORRA DE SERVICIO PNI MASC  	'],
            ['departamento_id'	=>	2	,'detalle' => '	PANTALON DE INSTRUCCIÓN MASCULINO   	'],
            ['departamento_id'	=>	2	,'detalle' => '	PANTALON DE INSTRUCCIÓN FEMENINO  	'],
            ['departamento_id'	=>	2	,'detalle' => '	PANTALON RECTO MASCULINO EN TEJIDO PALM-BEACH  	'],
            ['departamento_id'	=>	2	,'detalle' => '	PANTALON RECTO FEMENINO PALM-BEACH  	'],
            ['departamento_id'	=>	2	,'detalle' => '	POLAR INTERCUARTEL 	'],
            ['departamento_id'	=>	2	,'detalle' => '	TENIDA INSTRUCCIÓN NUEVO MODELO UNISEX	'],
            ['departamento_id'	=>	2	,'detalle' => '	TENIDA DE SALIDA FEMENINA EN PALM-BEACH (PANTALON, FALDA)	'],
            ['departamento_id'	=>	2	,'detalle' => '	TENIDA DE SALIDA MASCULINA EN PALM-BEACH   	'],
            ['departamento_id'	=>	2	,'detalle' => '	ZAPATO ELASTICADO PLANTA DE GOMA 	'],
            ['departamento_id'	=>	2	,'detalle' => '	BOTA DE MONTAÑA VERDE	'],
            ['departamento_id'	=>	2	,'detalle' => '	BOTIN OPERATIVO MEDIA CAÑA UNISEX	'],
            ['departamento_id'	=>	2	,'detalle' => '	NUEVA TENIDA MOTORISTA	'],
            ['departamento_id'	=>	2	,'detalle' => '	PARKA DE CAMPAÑA UNISEX	'],
            ['departamento_id'	=>	2	,'detalle' => '	POLERA OPERATIVA MASCULINA Y FEMENINA	'],
            ['departamento_id'	=>	2	,'detalle' => '	PANTALÓN OPERATIVO FEMENINO	'],
            ['departamento_id'	=>	2	,'detalle' => '	PANTALÓN OPERATIVO MASCULINO	'],
            ['departamento_id'	=>	2	,'detalle' => '	QUEPI OPERATIVO UNISEX	'],
            ['departamento_id'	=>	2	,'detalle' => '	TENIDA ALTA MONTAÑA	'],
            ['departamento_id'	=>	2	,'detalle' => '	AGUA 500 CC	'],
            ['departamento_id'	=>	2	,'detalle' => '	BANDERAS RASO Y ASTA METALICA CON CONDOR (SUBDIGCAR)	'],
            ['departamento_id'	=>	2	,'detalle' => '	BANDEROLA DE SOM	'],
            ['departamento_id'	=>	2	,'detalle' => '	CALCETÍN DE VESTIR UNISEX	'],
            ['departamento_id'	=>	2	,'detalle' => '	DELANTAL HOSCAR	'],
            ['departamento_id'	=>	2	,'detalle' => '	GIFT CARD (DEPTO. ASUNTOS INTERNOS)	'],
            ['departamento_id'	=>	2	,'detalle' => '	GUANTES DE TRABAJO	'],
            ['departamento_id'	=>	2	,'detalle' => '	MASCARILLA, RESPIRADOR Y FILTROS	'],
            ['departamento_id'	=>	2	,'detalle' => '	PALAS, PICOTAS, RASTRILLOS	'],
            ['departamento_id'	=>	2	,'detalle' => '	PIOCHAS ACRÍLICAS CORONEL Y SUBOFICIAL MAYOR	'],
            ['departamento_id'	=>	2	,'detalle' => '	PROTECTOR SOLAR	'],
            ['departamento_id'	=>	2	,'detalle' => '	SERVICIO ASEO DEPTO. L.2.	'],
            ['departamento_id'	=>	2	,'detalle' => '	SERVICIO TRANSPORTE MARITIMO PASAJEROS	'],
            ['departamento_id'	=>	2	,'detalle' => '	SERVICIO TRANSPORTE MARITIMO VEHICULOS	'],
            ['departamento_id'	=>	2	,'detalle' => '	SUMINISTRO SERVICIO RECARGA DE TARJETA ALIMENTACION	'],
            ['departamento_id'	=>	2	,'detalle' => '	SERVICIO DE DESTRUCCION DE VESTUARIO Y CALZADO	'],
            ['departamento_id'	=>	2	,'detalle' => '	TENIDAS A MEDIDA 	'],
            ['departamento_id'	=>	3	,'detalle' => '	LUBRICANTES 15W40	'],
            ['departamento_id'	=>	3	,'detalle' => '	LUBRICANTES 5W30	'],
            ['departamento_id'	=>	3	,'detalle' => '	LUBRICANTES 15W40 DIESEL	'],
            ['departamento_id'	=>	3	,'detalle' => '	REFRIGERANTE AD-BLUE	'],
            ['departamento_id'	=>	3	,'detalle' => '	MATERIALES DE OFICINA	'],
            ['departamento_id'	=>	3	,'detalle' => '	MATERIALES Y ÚTILES DE ASEO	'],
            ['departamento_id'	=>	3	,'detalle' => '	INSUMOS Y REPUESTOS COMPUTACIONALES	'],
            ['departamento_id'	=>	3	,'detalle' => '	INSUMOS ELÉCTRICOS 	'],
            ['departamento_id'	=>	3	,'detalle' => '	INSUMOS DE GRÁFICA Y PINTURA	'],
            ['departamento_id'	=>	3	,'detalle' => '	INSUMOS DE SOLDADURA Y VULCANIZACIÓN	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS PRIMARIOS MARCA DODGE	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS SECUNDARIOS MARCA DODGE	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS PRIMARIOS MARCA NISSAN	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS SECUNDARIOS MARCA NISSAN	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS MARCA CITROEN	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS MARCA HONDA	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS MARCA MERCEDES BENZ	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS PRIMARIOS MARCA HYUNDAI	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS SECUNDARIOS MARCA HYUNDAI	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS PRIMARIOS MARCA TOYOTA	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS SECUNDARIO MARCA TOYOTA.	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS PRIMARIOS MARCA FIAT	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS SECUNDARIO MARCA FIAT	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS PRIMARIO MARCA FORD	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS Y ACCESORIOS SECUNDARIO MARCA FORD	'],
            ['departamento_id'	=>	3	,'detalle' => '	ADQUISICIÓN DE FILTROS PARA STOCK DE BODEGA	'],
            ['departamento_id'	=>	3	,'detalle' => '	ADQUISICIÓN DE AMPOLLETAS, ÓPTICOS.	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 225-65-R17	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 235-65-R16	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 235-45-R17	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 235-65-R17	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 215-75-R16	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 195-75-R16	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 245-75-R16	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 205-55-R16	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 195-60-R15	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 195-55-R15	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 175-70-R14	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 225-60-R18	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 215-70-R15	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 215-75-R17.5	'],
            ['departamento_id'	=>	3	,'detalle' => '	NEUMÁTICO 225-55-R17	'],
            ['departamento_id'	=>	3	,'detalle' => '	BATERÍA 12 V 60 AH PERF. DERECHO BAJO	'],
            ['departamento_id'	=>	3	,'detalle' => '	BATERÍA 12V 90 AH PERF. DERECHO BAJO	'],
            ['departamento_id'	=>	3	,'detalle' => '	BATERÍA 12V 45 AH PERF. DERECHO BAJO	'],
            ['departamento_id'	=>	3	,'detalle' => '	BATERÍA 12V 65 AH AGM	'],
            ['departamento_id'	=>	3	,'detalle' => '	BATERÍA 12V 12 AH AGM	'],
            ['departamento_id'	=>	3	,'detalle' => '	REPUESTOS PARA EL PARQUE VEHICULAR MULTIMARCA REGIÓN METROPOLITANA	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENCIÓN Y REPARACIÓN PARQUE VEHICULAR MARCA DODGE	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENCIÓN Y REPARACIÓN PARQUE VEHICULAR MARCA MERCEDES BENZ	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENCIÓN Y REPARACIÓN PARQUE VEHICULAR MARCA NISSAN	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENCIÓN Y REPARACIÓN PARQUE VEHICULAR MARCA NISSAN X-TRAIL COLOR FABRICA	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENCIÓN Y REPARACIÓN PARQUE VEHICULAR MARCA FORD	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENCIÓN Y REPARACIÓN PARQUE VEHICULAR MARCA FIAT	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENCIÓN Y REPARACIÓN PARQUE VEHICULAR MARCA HYUNDAI	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENCIÓN Y REPARACIÓN PARQUE VEHICULAR MARCA MULTIMARCAS	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENIMIENTO Y REPARACIÓN VEHÍCULOS LANZA AGUA	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENIMIENTO Y REPARACIÓN VEHÍCULOS TÁCTICOS PANHARD	'],
            ['departamento_id'	=>	3	,'detalle' => '	CONTRATO DE SUMINISTRO INSTALACIÓN Y REAPARICIÓN DE PARABRISAS Y VIDRIOS VEHÍCULOS LIVIANOS	'],
            ['departamento_id'	=>	3	,'detalle' => '	CONTRATO DE SUMINISTRO DE PLACAS PATENTES INSTITUCIONALES PARA VEHÍCULOS DE CARGO DE CARABINEROS DE CHILE	'],
            ['departamento_id'	=>	3	,'detalle' => '	CONTRATO SUMINISTRO DE AGUA	'],
            ['departamento_id'	=>	3	,'detalle' => '	CONTRATO DE SERVICIOS DE ASEO PARA EL DPTO DE TRANSPORTES L.3	'],
            ['departamento_id'	=>	3	,'detalle' => '	CONTRATO ARRIENDO VEHICULOS MOTORIZADOS COMERCIAL OSSA LTDA.	'],
            ['departamento_id'	=>	3	,'detalle' => '	CONTRATO ARRIENDO VEHICULOS MOTORIZADOS UNIDADES ESPECIALIZADAS MITTA	'],
            ['departamento_id'	=>	3	,'detalle' => '	CONTRATO ARRIENDO VEHICULOS MOTORIZADOS TERESA GARRIDO LTDA.	'],
            ['departamento_id'	=>	3	,'detalle' => '	CONTRATO DE SERVICIO REVISIONES TÉCNICAS APPLUS S.A.	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENCIÓN Y REPARACIÓN (LANCHAS POLICIALES)	'],
            ['departamento_id'	=>	3	,'detalle' => '	MANTENCION Y REPARACION MAQUINAS	'],
            ['departamento_id'	=>	3	,'detalle' => '	ADQUISICIÓN DE FURGÓN POLICIAL (SUV 4X2 CON CALABOZO)	'],
            ['departamento_id'	=>	3	,'detalle' => '	ADQUISICIÓN DE RADIOPATRULLA SIN CALABOZO	'],
            ['departamento_id'	=>	3	,'detalle' => '	ADQUISICIÓN DE CAMIONETA POLICIAL AP	'],
            ['departamento_id'	=>	3	,'detalle' => '	ADQUISICIÓN DE CUARTEL MÓVIL	'],
            ['departamento_id'	=>	3	,'detalle' => '	ADQUISICIÓN DE MOTOCICLETA POLICIAL TODO TERRENO	'],
            ['departamento_id'	=>	3	,'detalle' => '	ADQUISICIÓN DE CAMIONETA 4X4, PROVISTA DE PROTECCIÓN ANTIBALÍSTICA NIVEL III	'],
            ['departamento_id'	=>	3	,'detalle' => '	ADQUISICIÓN DE CAMIONETA 4X4, PROVISTA DE PROTECCIÓN ANTIBALÍSTICA NIVEL III-A	'],
            ['departamento_id'	=>	3	,'detalle' => '	SERVICIO DE POLARIZADO 	'],
            ['departamento_id'	=>	3	,'detalle' => '	DISPENSADORES DE AGUA	'],
            ['departamento_id'	=>	3	,'detalle' => '	ZAPATOS DE SEGURIDAD	'],
            ['departamento_id'	=>	3	,'detalle' => '	OVEROLES 	'],
            ['departamento_id'	=>	3	,'detalle' => '	CARPAS DE VEHICULO	'],
            ['departamento_id'	=>	3	,'detalle' => '	VAJILLA	'],
            ['departamento_id'	=>	3	,'detalle' => '	TERMOS	'],
            ['departamento_id'	=>	3	,'detalle' => '	PROYECTORES DE AREA LED	'],
            ['departamento_id'	=>	3	,'detalle' => '	SET DE HERRAMIENTAS	'],
            ['departamento_id'	=>	3	,'detalle' => '	MATERIALES MANTENIMEINTO Y REPARACION DE CUARTEL	'],
            ['departamento_id'	=>	3	,'detalle' => '	AISLACION TERMICA TECHO BODEGA	'],
            ['departamento_id'	=>	3	,'detalle' => '	EXTINTORES 5KILOS PARA VEHICULOS	'],
            ['departamento_id'	=>	3	,'detalle' => '	CAMILLAS MECANICAS	'],
            ['departamento_id'	=>	3	,'detalle' => '	BALIZAS / SIRENAS	'],
            ['departamento_id'	=>	3	,'detalle' => '	ESTANQUE DE COMBUSTIBLE PORTATILES	'],
            ['departamento_id'	=>	3	,'detalle' => '	MICROONDAS 	'],
            ['departamento_id'	=>	4	,'detalle' => '	HENO DE ALFALFA  (KG)	'],
            ['departamento_id'	=>	4	,'detalle' => '	AVENA FORRAJERA (KG)	'],
            ['departamento_id'	=>	4	,'detalle' => '	PELLET ESTANDAR Y PELLET GESTACIÓN Y CRIANZA (KG)	'],
            ['departamento_id'	=>	4	,'detalle' => '	ALIMENTO CONCENTRADO CANES ADULTOS (KG)	'],
            ['departamento_id'	=>	4	,'detalle' => '	BUZOS DE ALTO VOLUMEN Y BUZOS DESECHABLES	'],
            ['departamento_id'	=>	4	,'detalle' => '	VESTUARIO PROTECTOR PARA CABALLAR	'],
            ['departamento_id'	=>	4	,'detalle' => '	ZAPATOS DE GOMA PARA CABALLAR	'],
            ['departamento_id'	=>	4	,'detalle' => '	PRODUCTOS FARMACEUTICOS	'],
            ['departamento_id'	=>	4	,'detalle' => '	MATERIALES Y UTILES QUIRURGICOS	'],
            ['departamento_id'	=>	4	,'detalle' => '	INSECTICIDA, RATICIDAS Y OTROS	'],
            ['departamento_id'	=>	4	,'detalle' => '	TUBOS CEBADEROS Y PROTECTORES AUDITIVOS	'],
            ['departamento_id'	=>	4	,'detalle' => '	VIRUTA DE MADERA (FARDOS)	'],
            ['departamento_id'	=>	4	,'detalle' => '	HERRADURAS, CLAVOS Y HERRAMIENTAS DE HERRAJE	'],
            ['departamento_id'	=>	4	,'detalle' => '	VALES DE GAS	'],
            ['departamento_id'	=>	4	,'detalle' => '	PELLET PERFOMANCE PARA CABALLARES (KG)	'],
            ['departamento_id'	=>	4	,'detalle' => '	ALIMENTO ESPECIAL DE CANES ADULTOS	'],
            ['departamento_id'	=>	4	,'detalle' => '	ALAMBRE GALVANIZADO	'],
            ['departamento_id'	=>	4	,'detalle' => '	FAJAS LUMBARES	'],
            ['departamento_id'	=>	4	,'detalle' => '	MATERIALES DE CONSTRUCCIÓN	'],
            ['departamento_id'	=>	4	,'detalle' => '	GUANTE DE CABRITILLA	'],
            ['departamento_id'	=>	4	,'detalle' => '	BOMBA DE AGUA PARA HARAS LAS ENCINAS	'],
            ['departamento_id'	=>	4	,'detalle' => '	SERVICIO CONSTRUCCIÓN DE POZOS EN HARAS SAUSALITO	'],
            ['departamento_id'	=>	4	,'detalle' => '	SERVICIO ELIMINACIÓN DE RESIDUOS	'],
            ['departamento_id'	=>	4	,'detalle' => '	ESCOFINA	'],
            ['departamento_id'	=>	4	,'detalle' => '	MARTILLO DE GOMA PARA HERRAJE	'],
            ['departamento_id'	=>	4	,'detalle' => '	CORTINAS PARA CASINO	'],
            ['departamento_id'	=>	4	,'detalle' => '	CAPAS IMPERMEABLES PARA CANES	'],
            ['departamento_id'	=>	4	,'detalle' => '	GRAMPAS PARA CERCO	'],
            ['departamento_id'	=>	4	,'detalle' => '	MATERIAL NIVELADOR	'],
            ['departamento_id'	=>	4	,'detalle' => '	EQUIPAMIENTO MÉDICO	'],
            ['departamento_id'	=>	4	,'detalle' => '	CUCHILLOS DESPALMADORES	'],
            ['departamento_id'	=>	4	,'detalle' => '	COLETO PARA HERRAR	'],
            ['departamento_id'	=>	4	,'detalle' => '	ACCESORIOS ELECTRICOS, SOPORTE PARA MOBILIARIO Y LETREROS	'],
            ['departamento_id'	=>	4	,'detalle' => '	MAQUINARIA PARA HERRAJE	'],
            ['departamento_id'	=>	4	,'detalle' => '	RECARGA DE BIDONES PARA AGUA	'],
            ['departamento_id'	=>	4	,'detalle' => '	MANTENCION DE VEHÍCULO	'],
            ['departamento_id'	=>	4	,'detalle' => '	ENCOMIENDAS	'],
            ['departamento_id'	=>	5	,'detalle' => '	LINTERNA PARA UNIDADES OPERATIVAS	'],
            ['departamento_id'	=>	5	,'detalle' => '	LENTE DE PROTECCIÓN VISUAL PARA UNIDADES OPERATIVAS	'],
            ['departamento_id'	=>	5	,'detalle' => '	DISPOSITIVO DE SUJECIÓN REMOTA (BOLA WRAP)	'],
            ['departamento_id'	=>	5	,'detalle' => '	AEROSOL OC PARA UNIDADES OPERATIVA	'],
            ['departamento_id'	=>	5	,'detalle' => '	PISTOLAS CALIBRE .40	'],
            ['departamento_id'	=>	5	,'detalle' => '	FUSIL CALIBRE 5,56	'],
            ['departamento_id'	=>	5	,'detalle' => '	MUNICIÓN CALIBRE 9MM	'],
            ['departamento_id'	=>	5	,'detalle' => '	PISTOLAS CALIBRE 9MM	'],
            ['departamento_id'	=>	5	,'detalle' => '	SUBAMETRALLADORA 9MM	'],
            ['departamento_id'	=>	5	,'detalle' => '	CASCO ANTIBALÍSTICO CON SISTEMA DE PROTECCIÓN FACIAL	'],
            ['departamento_id'	=>	5	,'detalle' => '	CHALECO ANTIBALAS INTERIOR, TIPO CAMISETA NIVEL III-A	'],
            ['departamento_id'	=>	5	,'detalle' => '	CHALECO ANTIBALAS NIVEL III-A  MODULAR	'],
            ['departamento_id'	=>	5	,'detalle' => '	BASTÓN RETRÁCTIL	'],
            ['departamento_id'	=>	5	,'detalle' => '	CINTURÓN TÁCTICO NUEVO MODELO CON FUNDA DE POLIMERO	'],
            ['departamento_id'	=>	5	,'detalle' => '	POLVO QUIMICO CS	'],
            ['departamento_id'	=>	5	,'detalle' => '	BALACLAVA	'],
            ['departamento_id'	=>	5	,'detalle' => '	SISTEMA TRASMISOR DE ENERGIA DE ALTA PRESIÓN	'],
            ['departamento_id'	=>	5	,'detalle' => '	BLANCOS PARA PRÁCTICA DE TIRO POLICIAL 	'],
            ['departamento_id'	=>	5	,'detalle' => '	MATERIALES TALABARTERIÍA 	'],
            ['departamento_id'	=>	5	,'detalle' => '	COLETOS CABRITILLA PARA SOLDAR Y COTONA DE TRABAJO	'],
            ['departamento_id'	=>	5	,'detalle' => '	ACEITE DE MOTOR Y LUBRICANTE	'],
            ['departamento_id'	=>	5	,'detalle' => '	SAL DE PAVÓN; PAVÓN RÁPIDO ; ALCOHOL ISOPROPILICO 	'],
            ['departamento_id'	=>	5	,'detalle' => '	GUANTES DE NITRILO; GUANTES DESECHABLES DE LÁTEX	'],
            ['departamento_id'	=>	5	,'detalle' => '	MATERIALES DE ASEO	'],
            ['departamento_id'	=>	5	,'detalle' => '	TÓNER Y CARTRIDGE	'],
            ['departamento_id'	=>	5	,'detalle' => '	RESMAS DE PAPEL OFICIO	'],
            ['departamento_id'	=>	5	,'detalle' => '	CHOLGUAN PRACTICA DE TIRO	'],
            ['departamento_id'	=>	5	,'detalle' => '	ALAMBRE	'],
            ['departamento_id'	=>	5	,'detalle' => '	MATERIALES VARIOS	'],
            ['departamento_id'	=>	5	,'detalle' => '	HERRAMIENTAS	'],
            ['departamento_id'	=>	5	,'detalle' => '	IONIZADOR DE ESCRITORIO 220V	'],
            ['departamento_id'	=>	5	,'detalle' => '	DISPENSADOR DE AGUA FRÍA/CALIENTE	'],
            ['departamento_id'	=>	5	,'detalle' => '	BATERÍAS RECARGABLES AA	'],
            ['departamento_id'	=>	5	,'detalle' => '	SCUBA	'],
            ['departamento_id'	=>	5	,'detalle' => '	KIT DLG	'],
            ['departamento_id'	=>	5	,'detalle' => '	CILINDO NITROGENO	'],
            ['departamento_id'	=>	5	,'detalle' => '	CARPA TIPO ARAÑA TRIPLE	'],
            ['departamento_id'	=>	5	,'detalle' => '	KIT IFEX	'],
            ['departamento_id'	=>	5	,'detalle' => '	BIDONES DE AGUA PURIFICADA	'],
            ['departamento_id'	=>	5	,'detalle' => '	MANTENCIÓN PREVENTIVA Y CORRECTIVA	'],
            ['departamento_id'	=>	5	,'detalle' => '	MANTENCIÓN EQUIPOS IFEX	'],
            ['departamento_id'	=>	5	,'detalle' => '	CONTRATACIÓN DEL SERVICIO DE MANTENCIÓN DE BOTELLAS DE ARGÓN	'],
            ['departamento_id'	=>	5	,'detalle' => '	CONTRATACIÓN DEL SERVICIO DE MANTENCIÓN DE BOTELLAS DE CO2	'],
            ['departamento_id'	=>	5	,'detalle' => '	CONTRATACIÓN DEL SERVICIO DE MANTENCIÓN DE BOTELLAS DE NITRÓGENO	'],
            ['departamento_id'	=>	5	,'detalle' => '	MANTENIMIENTO POLIGONOS VIRTUALES	'],
            ['departamento_id'	=>	5	,'detalle' => '	MANTENIMIENTO IMPRESORAS	'],
            ['departamento_id'	=>	5	,'detalle' => '	CONTRATACIÓN DEL SERVICIO DE ASEO	'],
            ['departamento_id'	=>	5	,'detalle' => '	PASAJES MARÍTIMOS NACIONALES	'],
            ['departamento_id'	=>	5	,'detalle' => '	SERVICIO DE DESTRUCCIÓN DE MATERIAL POLICIAL	'],
            ['departamento_id'	=>	5	,'detalle' => '	SERVICIO DE DESTRUCCIÓN DE MATERIAL POLICIAL AUMENTO 30%	'],
            ['departamento_id'	=>	5	,'detalle' => '	CONTRATACIÓN DEL SERVICIO DE VIGILANCIA	'],
            ['departamento_id'	=>	5	,'detalle' => '	MUNICIÓN CALIBRE .380 AUTO	'],
            ['departamento_id'	=>	5	,'detalle' => '	SILUETAS PRÁCTICAS DE TIRO	'],
            ['departamento_id'	=>	5	,'detalle' => '	MUNICIÓN CALIBRE  6MM. BR.	'],
            ['departamento_id'	=>	5	,'detalle' => '	EXTINTORES DE PERSONALES	'],
            ['departamento_id'	=>	5	,'detalle' => '	LÍQUIDO ASEO ARMAMENTO	'],
            ['departamento_id'	=>	5	,'detalle' => '	ESCUDOS ANTIDISTURBIOS	'],
            ['departamento_id'	=>	5	,'detalle' => '	DISPOSITIVO DE SUJECIÓN REMOTA (BOLA WRAP) NUEVO PROCESO	'],
            ['departamento_id'	=>	5	,'detalle' => '	CASCO ANTIBALÍSTICO CON SISTEMA DE PROTECCIÓN FACIAL (AUMENTO 30%)	'],
            ['departamento_id'	=>	5	,'detalle' => '	POLÍGONO VIRTUAL	'],
            ['departamento_id'	=>	6	,'detalle' => '	SEGUROS CUARTELES INST. Y SU CONTENIDO	'],
            ['departamento_id'	=>	6	,'detalle' => '	SEGUROS VEHÍCULOS INST. COMANDO	'],
            ['departamento_id'	=>	6	,'detalle' => '	SEGUROS CASAS ANEXAS INST.	'],
            ['departamento_id'	=>	6	,'detalle' => '	SEGUROS CASCO AEREOS INST.	'],
            ['departamento_id'	=>	6	,'detalle' => '	SEGUROS CASCOS MARÍTIMOS INST.	'],
            ['departamento_id'	=>	6	,'detalle' => '	SEGUROS VIVIENDAS FISCALES INST.	'],
            ['departamento_id'	=>	6	,'detalle' => '	SEGUROS OBLIGATORIO DE ACCIDENTES PERSONALES (SOAP)	'],
            ['departamento_id'	=>	6	,'detalle' => '	SEGUROS EQUIPO TECNOLOGICO Y EQUIPOS LABOCAR	'],
            
       
        ];


        // Insertar los departamentos en la base de datos
        foreach ($especies as $especie) {
            Especie::create([
                'detalle' => $especie['detalle'],
                'departamento_id' => $especie['departamento_id'],
            ]);
        }
    }
}
